apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-brewery
config:
  client_id: "kong"
  client_secret: "a8Jh6Z6dSxxufKlSB55u8yhdySkyWHZ5"
  discovery: "http://keycloak.iam/realms/brewery/.well-known/openid-configuration"
  introspection_endpoint: "http://keycloak.iam/realms/brewery/protocol/openid-connect/token/introspect"
  bearer_only: "yes"
  bearer_jwt_auth_enable: "yes"
  bearer_jwt_auth_allowed_auds:
    - account
plugin: oidc
