apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewery
spec:
  selector:
    matchLabels:
      app: brewery
  template:
    metadata:
      labels:
        app: brewery
    spec:
      containers:
        - name: brewery
          image: brewery
          resources:
            requests:
              cpu: "0.5"
              memory: 512Mi
            limits:
              cpu: "0.5"
              memory: 1Gi
          env:
            - name: LOGGING_LEVEL_GURU_SPRINGFRAMEWORK_SFGRESTBREWERY
              value: "info"
            - name: SERVER_SHUTDOWN
              value: "graceful"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: brewery
  annotations:
    # konghq.com/plugins: prometheus-brewery,brewery-logs
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    app: brewery
    stack: echo
    interface: rest
    language: java
spec:
  type: LoadBalancer
  selector:
    app: brewery
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
