apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: brewery-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brewery
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
