apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    app: brewery
    stack: echo
    interface: rest
    language: java
  name: brewery
spec:
  type: LoadBalancer
  selector:
    app: brewery
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
