apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewery
spec:
  selector:
    matchLabels:
      app: brewery
  template:
    metadata:
      labels:
        app: brewery
    spec:
      containers:
        - name: brewery
          image: sidartasilva/sfg-beer-works:0508f8077be76d5c7dac9f06c16f346507955c3c
          resources:
            requests:
              cpu: "0.05"
              memory: 512Mi
            limits:
              cpu: "0.05"
              memory: 1Gi
          env:
            - name: LOGGING_LEVEL_GURU_SPRINGFRAMEWORK_SFGRESTBREWERY
              value: info
          ports:
            - containerPort: 8080