apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewery
spec:
  selector:
    matchLabels:
      app: brewery
  template:
    metadata:
      labels:
        app: brewery
    spec:
      containers:
        - name: brewery
          image: sidartasilva/sfg-beer-works:d2321abde9424c3b2050d6df8ab0425078a63c10
          resources:
            requests:
              cpu: "0.1"
              memory: 512Mi
            limits:
              cpu: "0.5"
              memory: 512Mi
          env:
          - name: LOGGING_LEVEL_GURU_SPRINGFRAMEWORK_SFGRESTBREWERY
            value: "info"
          - name: SERVER_SHUTDOWN
            value: "graceful"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          ports:
            - containerPort: 8080