kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: data
  namespace: logs
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.gke.io/zone
        values:
          - us-central1-a
          - us-central1-b
          - us-central1-c
