apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brewery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: k8s
    repoURL: https://github.com/maratonafullcyclesidartaoss/sfg-beer-works.git
    targetRevision: HEAD
    kustomize:
  destination:
    namespace: brewery
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

