extends: [[spectral:oas, all]]
rules:
  info-contact: error
  tags-should-have-description:
    description: Tags must have a description.
    given: $.tags[*]
    severity: error
    then:
      field: description
      function: truthy

  contact-properties:
    description: Contact object must have "name", "url", and "email".
    given: $.info.contact
    severity: error
    then:
      - field: name
        function: truthy
      - field: url
        function: truthy
      - field: email
        function: truthy

  operations-description-non-null:
    description: Operation "description" must be informed.
    given: $.paths[*][get,post,put,delete,options]
    severity: error
    then:
      - field: description
        function: truthy

  operations-summary-non-null:
    description: Operation "summary" must be informed.
    given: $.paths[*][get,post,put,delete,options]
    severity: error
    then:
      - field: summary
        function: truthy
